### ISSUE TITLE
[Feature] Show a preview window listing all of the files and occurrences where the symbol will be replaced

### ISSUE THREAD

**Issue by pidgeon777** [smjonas/inc-rename.nvim#19]
It would be great for this plugin to show a rename preview panel similar to the quick fix one, containing a row for each of the symbols which will be updated with the LSP rename.

Also, those rows should be grouped in files where the change will occur. Example:

```
-----------------
-- Preview Window
-----------------

[1] C:\Work\include.h [1 match]
17. int NEWSYMBOL;

[2] C:\Work\main.c [2 matches]
19.   NEWSYMBOL = 12;
23.       print("Today is &d", NEWSYMBOL\n");
```

**Comment by smjonas** [comment]
Seems like a nice feature to have! Did I understand you correctly that this preview feature should be shown as a sort of confirmation dialog when you press enter? And then you would need to press again?

**Comment by smjonas** [comment]
Hey @pidgeon777, are you still interested in this feature?

**Comment by pidgeon777** [comment]
> Hey @pidgeon777, are you still interested in this feature?

Hi @smjonas sorry for the wait, somehow I missed the updates on this issue.

Well, yes, I would be highly interested.

> Seems like a nice feature to have! Did I understand you correctly that this preview window should be shown as a sort of confirmation dialog when you press enter? And then you would need to press enter (or y) again?

What I meant, is that it could be used in two ways:

a. Show a live preview of the changes introduced with the LSP rename feature when typing the new variable name.
b. Show a preview confirmation dialog just showing the new changes before applying them.

In both cases, it would be necessary to show the preview of the newly modified code _before_ applying the changes.

And this could be a live preview (as expressed in case `a`) or just a confirmation (case `b`).

Also, it would be really nice to show all of those changes in the way I described them in my first post so that it would be possible to know in an easy way which files would get modified, for example.

**Comment by pidgeon777** [comment]
I would be happy to help you beta-testing this new feature, if needed 👍.

**Comment by folke** [comment]
At least for the current file, this is already possible. See `:h command-preview`:

```
4. Return an integer (0, 1, 2) which controls how Nvim behaves as follows:
   0: No preview is shown.
   1: Preview is shown without preview window (even with "inccommand=split").
   2: Preview is shown and preview window is opened (if "inccommand=split").
      For "inccommand=nosplit" this is the same as 1.
```

You should probably return `2` at https://github.com/smjonas/inc-rename.nvim/blob/de322174a1adc8527b3805dd01e18a7f4ffec22b/lua/inc_rename/init.lua#L319

**Comment by folke** [comment]
> I am already returning 2 (not in the function being executed but in the preview callback):
My bad, looked at the wrong code :)

@pidgeon777 probably doens't have `inccommand=split` set.

**Comment by pidgeon777** [comment]
I'm trying to test the branch but noice seems to crash when I select "Yes" "No" in the new user choice popup, or when I try to autocomplete, or when activating a previous command from the history etc.

**Comment by pidgeon777** [comment]
In particular, in the new noice popup, when I digit `:IncRename` and then a `space`, Neovim (Neovide) crashes when pressing `space`.

**Comment by smjonas** [comment]
I can't reproduce the crash with `noice` (NVIM v0.9.0-dev-98-g1c478391c). Can you create an issue on the noice repo with the exact error message?

**Comment by pidgeon777** [comment]
In the meanwhile I disabled `noice` and `inc-rename.nvim` doesn't lead Neovim to crash anymore. Here is the result when trying to rename a function:

![image](https://user-images.githubusercontent.com/13739892/199702177-8ee2272f-f707-45d6-be4f-b1c37f5bfafb.png)

Now I will test your PR.

**Comment by folke** [comment]
@pidgeon777 Neovide is not working properly with Noice. See the tracking issue on the noice github. Disable multigrid and use Neovim nightly is you want to use Noice.

**Comment by pidgeon777** [comment]
Thanks @folke, I'll try to report any found issue in the `Noice` issue tracker 👍.
