### ISSUE TITLE
In a typescript file, cancelling IncRename results in an error

### ISSUE THREAD

**Issue by NullVoxPopuli** [smjonas/inc-rename.nvim#2]
I'm pressing escape to try to abort renaming in a typescript file. All the same info as here: https://github.com/smjonas/inc-rename.nvim/issues/1 -- might be related.

Works as expected in lua files

**Comment by smjonas** [comment]
Can you check if the latest commit fixes this issue as well?

**Comment by NullVoxPopuli** [comment]
it works! thanks!
