### ISSUE TITLE
Integration with indent-blanklines

### ISSUE THREAD

**Issue by UtkarshVerma** [smjonas/inc-rename.nvim#29]
Currently, if I use this plugin, the indent guidelines from [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) are hidden.

![image](https://user-images.githubusercontent.com/31820255/213906400-9f64ed3f-206f-48a9-ab28-6229a2acdc94.png)

How can I make it so that the indent lines are shown during the rename?

**Comment by smjonas** [comment]
Thanks for reporting! Should be fixed now:
![image](https://user-images.githubusercontent.com/40792180/213926510-7c0b7b37-b26d-4a52-8f1a-3f553e31872c.png)

**Comment by UtkarshVerma** [comment]
It works now, thanks for the quick fix.
