### ISSUE TITLE
Renaming in bash has some weird offset issue?

### ISSUE THREAD

**Issue by NullVoxPopuli** [smjonas/inc-rename.nvim#3]
I don't know how to describe this so here is a gif/recording:

https://user-images.githubusercontent.com/199018/171970255-93fbb717-584f-4682-99b2-77e5998571af.mp4

**Comment by smjonas** [comment]
Could you please send me the code snippet you are using to reproduce this?

**Comment by NullVoxPopuli** [comment]
Yeah, it's here: https://github.com/NullVoxPopuli/dotfiles/blob/main/home/scripts/markdown#L16
