### ISSUE TITLE
Should not cause any error when trying to `<C-p>` after entering command mode by `:`

### ISSUE THREAD

**Issue by nyngwang** [smjonas/inc-rename.nvim#31]
Say I just rename a variable. Then, if I accidentally press`<C-p>`(to get the last command I called) too many times, then the renaming prompt will show up again and give me an error:

- The plugin I use to show message is `folke/noice.nvim`, which might be related.
- Here the `restore_view_on_zoom_out` is the variable name I just named.

This bug is really annoying since the LSP client will simply stop working after the error. I hope it could be fixed soon...

```
   Error  14:03:00 msg_show.lua_error    restore_view_on_zoom_out Error executing vim.schedule lua callback: BufEnter Autocommands for "*": Vim(lua):E5108: Error executing lua Vim:E903: Process failed to start: too many open files: "/usr/bin/git"
stack traceback:
	[C]: in function 'jobstart'
	...l/share/nvim/lazy/lualine.nvim/lua/lualine/utils/job.lua:9: in function 'start'
	...zy/lualine.nvim/lua/lualine/components/diff/git_diff.lua:133: in function 'update_git_diff'
	...zy/lualine.nvim/lua/lualine/components/diff/git_diff.lua:121: in function 'update_diff_args'
	[string ":lua"]:1: in main chunk
	[C]: in function 'bufload'
	.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:55: in function 'cache_lines'
	.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:121: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
	[C]: in function 'bufload'
	.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:55: in function 'cache_lines'
	.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:121: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by smjonas** [comment]
I could not reproduce your error with `noice.nvim`. See this recording:

https://user-images.githubusercontent.com/40792180/215069940-c9c5b4ac-23ea-4d08-8619-56d0a1f5f295.mp4

Since there is this line in the error message "	...l/share/nvim/lazy/lualine.nvim/lua/lualine/utils/job.lua:9: in function 'start'", can you share your `lualine` config? Also the `noice` config might be useful as well.
