### ISSUE TITLE
start_row out of bounds error in function 'apply_highlights_fn'

### ISSUE THREAD

**Issue by linrongbin16** [smjonas/inc-rename.nvim#32]
Hi, I'm using inc-rename with dressing, following instructions in README.

Here's the error message when press <CR> to confirm rename:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/6496887/215306631-47fa6e8e-318a-419d-a6a7-7015c2793de0.png">

**Comment by smjonas** [comment]
Thanks for reporting, I made a silly mistake in the previous commit. Fixed now!
