### ISSUE TITLE
Keymap doesn't work

### ISSUE THREAD

**Issue by TroySigX** [smjonas/inc-rename.nvim#34]
The keymap `vim.keymap.set("n", "<leader>rn", ":IncRename ")`  gives the error: `E471: Argument required`

**Comment by smjonas** [comment]
Try `<leader>rn` while your cursor is above a variable. The argument to the `:IncRename` command (which this keymap opens) should be the renamed variable name, e.g. do `:IncRename new_name<enter>.`

**Comment by smjonas** [comment]
> Sorry for bumping this after a year but I'm getting this error now
> ![image](https://github.com/smjonas/inc-rename.nvim/assets/34080311/f7ef9fa1-3575-48d3-bfce-70ece2f4ad5a)
> 
> I works the first time but doesn't afterwards. Tried reopening `neovim` and it's still doesn't work.

So did you type the command like `:IncRename<enter>` or did you write any arguments after the command name? You need to specify the variable name after the command.

**Comment by marcus-dc** [comment]
I wasn't really able to complete the command. When I type `:Inc` it looks like it automatically enters it (I'm not really sure tho). Also happens when I try to use the keymap that was in the docs `<leader>rn` (Browsed my keymaps just to be sure it wasn't doubled up with some other keymap).

**Comment by heygwangjin** [comment]
> I wasn't really able to complete the command. When I type `:Inc` it looks like it automatically enters it (I'm not really sure tho). Also happens when I try to use the keymap that was in the docs `<leader>rn` (Browsed my keymaps just to be sure it wasn't doubled up with some other keymap).

Hello. Did you fix this issue?? I have same issue for it.
