### ISSUE TITLE
Rust - Inlined format args not renamed

### ISSUE THREAD

**Issue by ConnorWay32** [smjonas/inc-rename.nvim#39]
Renaming a variable with uninlined format args works as expected, however inlined format args are not affected.
```rust
let a = 5;
println!("{}", a);
println!("{a}");
```
becomes
```rust
let b = 5;
println!("{}", b);
println!("{a}");
```

**Comment by smjonas** [comment]
This is a `rust-analyzer` issue. Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11296.
