### ISSUE TITLE
Filling in the command line didn't work, but I fixed it

### ISSUE THREAD

**Issue by pillmuncher** [smjonas/inc-rename.nvim#41]
This didn't work:

```lua
function()
    return ":IncRename " .. vim.fn.expand("<cword>")
end
```

It had no observable effect whatsoever.

`vim.api.nvim_feedkeys()` to the rescue:

```lua
function()
    local line = ":IncRename " .. vim.fn.expand("<cword>")
    vim.api.nvim_feedkeys(line, "n", true)
end
```

I don't know if it was my Neovim version (0.9.2) or some other plugin interfering, but now it's working.

**Comment by smjonas** [comment]
Glad it's working for you now! Does it also not work if you pass `expr = true` to `vim.keymap.set`?

**Comment by pillmuncher** [comment]
Yes, you're right. It was the `expr = true`. I'm using lazy.nvim as my plugin manager and accidentally had it written like this:

```lua
-- plugins/inc_rename.lua
return {
    "smjonas/inc-rename.nvim",
    opts = {},
    keys = {
        {
            "<leader>rn",
            function()
                return ":IncRename " .. vim.fn.expand("<cword>")
            end,
            desc = "[r]e[n]ame",
            mode = { "n" },
           { expr = true },  --  <------------------ 
        },
    },
}
```

Changing it to 

```lua
           expr = true,
```

fixed it. My bad.
