### ISSUE TITLE
Bug: Renaming Variables Longer than Indent Causes Error with Preview

### ISSUE THREAD

**Issue by DrPoppyseed** [smjonas/inc-rename.nvim#47]
Hello! I love this plugin!

There seems to be an issue when renaming variables that are longer than the indent, as shown in the video.

https://github.com/smjonas/inc-rename.nvim/assets/44737273/ebdbd835-b819-40c0-b24f-79e145d59938

```sh
$ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

My neovim config at the time of reporting this issue: https://github.com/DrPoppyseed/config/tree/a88db7befae3985fcfd9998b10cf6f11998ad82d/dot_config/nvim

**Comment by smjonas** [comment]
Thanks for reporting, should be fixed now :)
