### ISSUE TITLE
Question about multiple buffers renaming

### ISSUE THREAD

**Issue by pidgeon777** [smjonas/inc-rename.nvim#52]
I've a question, what if the LSP rename action involves updating references in buffers different from the actual one?

It would be nice to have a preview of the changes which would be applied to the other buffers (opened or not). Would something like that possible?

**Comment by xzbdmw** [comment]
Ideally a diff view showing all related files is better, I also want something similar in community

**Comment by pidgeon777** [comment]
Maybe this library could be used, if or when supporting diff mode:

https://www.reddit.com/r/neovim/comments/1bkb981/introducing_nuicomponents_a_library_that/

**Comment by xzbdmw** [comment]
So cool, I’ll try to integrate it, there are many ideas comes up!

**Comment by smjonas** [comment]
Hi, did you know that `inc-rename` already supports a basic preview? The preivew is used if you set `:set inccommand=split`.
![image](https://github.com/smjonas/inc-rename.nvim/assets/40792180/36cf0324-09a1-4b3b-8561-ffe3626d52b1)

**Comment by xzbdmw** [comment]
> Hi, did you know that `inc-rename` can already show additional info about the files when renaming variables across multiple files? The split window will be shown if you set `:set inccommand=split`. ![image](https://private-user-images.githubusercontent.com/40792180/318200928-36cf0324-09a1-4b3b-8561-ffe3626d52b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MTExOTUsIm5iZiI6MTcxMTgxMDg5NSwicGF0aCI6Ii80MDc5MjE4MC8zMTgyMDA5MjgtMzZjZjAzMjQtMDlhMS00YjNiLTg1NjEtZmZlMzYyNmQ1MmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE1MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyN2JhYTM4NzBhZjBmMzI4ZDgyOWU3ZmM2YTQ0Njk4ZDUzM2I1Yzk3MDYwZmIzNTA0MzIyYzExM2ZjMjRkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7jkeeLhFEMuQojx0EgmcgByhs0R970Pf9J40BlDRok0)

Didn't know that!

**Comment by smjonas** [comment]
> Didn't know that!

I will add a note to the readme to make more users aware of this feature. However, while testing it, I noticed some buggy highlights which I will fix first.
