### ISSUE TITLE
How to change startup mode from insert to normal?

### ISSUE THREAD

**Issue by utrumo** [smjonas/inc-rename.nvim#58]
When I call the rename command, the pop-up window for renaming opens in insert mode.

Quite often I just have to go to the letter and replace it to fix the typo. In insert mode, using the arrows is very inconvenient.

How to change the mode to normal when a pop-up window appears?

I use this plugin with LazyVim with default config:
https://www.lazyvim.org/extras/editor/inc-rename

**Comment by smjonas** [comment]
Currently, I don't think this is possible since the command preview feature of Neovim that `inc-rename` uses, only works in command line mode. So you are actually in command line mode the whole time, not insert mode. Maybe it is possible to navigate in the `noice.nvim` window? Not sure

**Comment by hadynz** [comment]
Agreed. It would be great if the pop-up supports normal and insert mode, with config of what the default mode is

**Comment by erlangparasu** [comment]
i need block all text by default, so the text can be replaced faster

**Comment by smjonas** [comment]
> i need block all text by default, so the text can be replaced faster

That's impossible to achieve currently as the command preview only works in command line mode.

**Comment by Diaoul** [comment]
I was looking for this option as well, too bad it's not supported because the plugin is very convenient!

I'll stick to `vim.lsp.buf.rename` which allows me to switch to normal mode.
