### ISSUE TITLE
Treesitter integration?

### ISSUE THREAD

**Issue by kuator** [smjonas/inc-rename.nvim#6]

**Comment by smjonas** [comment]
Could you please clarify what exactly you would like to see as a feature? Treesitter does not care about semantics of your code, only the syntax. Semantics are handled by the language server.

**Comment by kuator** [comment]
https://github.com/nvim-treesitter/nvim-treesitter-refactor#smart-rename treesitter seems to provide renaming support, so I thought it could be used as a fallback if, let's say, the LSP server doesn't provide the "rename" capability
