### ISSUE TITLE
Execute `post_hook` even when canceled

### ISSUE THREAD

**Issue by eth3lbert** [smjonas/inc-rename.nvim#61]
Thank you for the great plugin!

I would like to suggest that the `post_hook` also be executed when the operation is canceled. Consider a scenario where we set `inccommand` to `split` and reset it in `post_hook`. Currently, `post_hook` only runs when the operation is executed successfully, which means it won't reset `inccommand` if `inc-rename` is canceled.

**Comment by smjonas** [comment]
Thanks for the suggestion! Given your scenario, when would you set `inccommand` to `split`? It seems like your use case would also require a `pre_hook` callback to set `inccommand` to `split` before starting the renaming before resetting it in `post_hook`. Could you clarify that before I change the `post_hook` behavior?

**Comment by eth3lbert** [comment]
Sure, I would expect something similar to the following should work:
``` lua
local user = {}

return {
  "smjonas/inc-rename.nvim",
  cmd = { "IncRename" },
  keys = {
    {
      "<leader>rn",
      function()
        user.inccommand = vim.o.inccommand
        vim.o.inccommand = "split"
        return ":IncRename " .. vim.fn.expand "<cword>"
      end,
      desc = "Lsp: Rename",
      expr = true,
    },
  },
  opts = {
    preview_empty_name = true,
    save_in_cmdline_history = false,
    input_buffer_type = "inc-rename",
    post_hook = function()
      vim.o.inccommand = user.inccommand
    end,
  },
}
```
Does this make sense to you?

**Comment by smjonas** [comment]
Yes that makes sense, thanks for clarifiying. Would the following work for you?
```lua
vim.api.nvim_create_autocmd("CmdLineLeave", {
  callback = function()
    vim.o.inccommand = user.inccommand
  end,
})
```
You could even be more advanced and only reset `inccommand` if the last command was "IncRename", e.g., using `vim.fn.histget(":")`, although I don't think that's necessary for your use case.

The reason I don't want to change the current behavior of `post_hook` is because it would break code of existing users that didn't add a nil check.
