### ISSUE TITLE
[Feature] Is it possible to change the size of the preview window?

### ISSUE THREAD

**Issue by DMunkei** [smjonas/inc-rename.nvim#62]
When I'm renaming something and the change is among multiple files, it does not show all of the places the change will occur. This is due to the fact, that the preview window is too small.

I tried setting `previewheight` to a different value per default it's on. `12` That didn't seem to do the trick. Any ideas what could be done?

**Comment by smjonas** [comment]
I couldn't find the option for this in the docs. Maybe you can ask on Reddit / Matrix if this is possible

**Comment by smjonas** [comment]
I found out it is possible by using `:set cmdwinheight=20`
