### ISSUE TITLE
When renaming from the middle of a variable name, the cursor experiences abnormal jitter.

### ISSUE THREAD

**Issue by ysl2** [smjonas/inc-rename.nvim#63]
https://github.com/user-attachments/assets/ab48b59e-f21f-4f5a-b614-b23131f3a1c4

**Comment by smjonas** [comment]
Hi, are you using the `dressing.nvim` integration by any chance?

**Comment by ysl2** [comment]
No, I didn't install `dressing.nvim`. Here are the plugins I installed:

**Comment by smjonas** [comment]
This appears to be an upstream issue which I reported here: https://github.com/neovim/neovim/issues/30696

**Comment by smjonas** [comment]
This bug has since been fixed in Neovim nightly
