### ISSUE TITLE
Support for aliases

### ISSUE THREAD

**Issue by Dexus0** [smjonas/inc-rename.nvim#65]

**Comment by smjonas** [comment]
Could you clarify what you would like to be implemented?

**Comment by Dexus0** [comment]
In Rust, you cannot rename the name you import a type as; for example:

```rust
use std::collections::Vec as Array;

struct foo {
    vec: Array
}
```
You cannot rename the `Array` type here.

**Comment by smjonas** [comment]
Adding support for aliases is up to the rust-analyzer language server to implement. However, I added a check that will cancel the rename early if the symbol under the cursor cannot be renamed.
