### ISSUE TITLE
Plugins fails

### ISSUE THREAD

**Issue by ajmasia** [smjonas/inc-rename.nvim#67]
When I call the plugin using LazyVim I get this error:
```bash
Error executing Lua callback: /opt/nvim-linux64/share/nvim/runtime/lua/vim/lsp/rpc.lua:291: Cannot serialise function: type not supported
stack traceback:
	[C]: in function 'encode'
	/opt/nvim-linux64/share/nvim/runtime/lua/vim/lsp/rpc.lua:291: in function 'encode_and_send'
	/opt/nvim-linux64/share/nvim/runtime/lua/vim/lsp/rpc.lua:338: in function 'request'
	/opt/nvim-linux64/share/nvim/runtime/lua/vim/lsp/client.lua:679: in function 'request'
	/opt/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:877: in function 'buf_request'
	...vim-lazyvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:516: in function 'perform_lsp_rename'
	...vim-lazyvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:564: in function 'incremental_rename_execute'
	...vim-lazyvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:577: in function <...vim-lazyvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:576>
```

**Comment by tizot** [comment]
Same for me:

- `inc-rename` version: "main" (hash `b0d5b5b`)
- LazyVim version: 13.5.3 (hash `adcbfc7`)

Additionally, when I trigger a rename with the key binding, the floating window does not appear until I press another key.
I don't know if it is a LazyVim or a IncRename issue though.

**Comment by kvarenzn** [comment]
same issue

changing `not vim.fn.has("nvim-0.11")` on line 157 of `init.lua` to `vim.fn.has("nvim-0.11") == 0` can temporarily solve this issue

**Comment by smjonas** [comment]
Sorry guys, that shouldn't have happened :sweat_smile: 

> changing `not vim.fn.has("nvim-0.11")` on line 157 of `lua/inc_rename/init.lua` to `vim.fn.has("nvim-0.11") == 0` can temporarily solve this issue

Thanks @kvarenzn, that must have slipped through during the last PR. I just pushed a hotfix changing it to `vim.fn.has("nvim-0.11") == 0`. Can you confirm that the issue is fixed now?

**Comment by smjonas** [comment]
Btw, which Neovim version are you using? If it's an older nightly version, I am thinking to revert the latest commit (which only works on the latest nightly version) due to the high number of complaints.

**Comment by ajmasia** [comment]
Thanks guys!

**Comment by tizot** [comment]
> Can anyone confirm that the issue is fixed now?

It works again. Thanks for the quick turnaround!
