### ISSUE TITLE
Errors when trying to rename stuff in markdown files

### ISSUE THREAD

**Issue by NullVoxPopuli** [smjonas/inc-rename.nvim#8]
Given this markdown file:
~~~md
# How To Contribute

## Installation

- `git clone <repository-url>`
- `cd @embroider/util`
- `yarn install`

## Linting

- `yarn lint:hbs`
- `yarn lint:js`
- `yarn lint:js --fix`

## Running tests

- `ember test` – Runs the test suite on the current Ember version
- `ember test --server` – Runs the test suite in "watch mode"
- `ember try:each` – Runs the test suite against multiple Ember versions

## Running the dummy application

- `ember serve`
- Visit the dummy application at [http://localhost:4200](http://localhost:4200).

For more information on using ember-cli, visit [https://ember-cli.com/](https://ember-cli.com/).
~~~

I tried to rename `yarn` to `pnpm` and got a bunch of errors

**Comment by smjonas** [comment]
Which language server are you using for Markdown files? (`:LspInfo`)

**Comment by NullVoxPopuli** [comment]
I don't have one setup atm

**Comment by smjonas** [comment]
https://user-images.githubusercontent.com/40792180/172122927-8a9fa38d-fadb-485f-82bc-49e73efae403.mp4

I can't reproduce your issue since tailwindcss does not seem to support renaming in Markdown files so the rename command will simply do nothing. Which exact errors are shown to you?

**Comment by smjonas** [comment]
Are you still experiencing this issue?

**Comment by NullVoxPopuli** [comment]
I am not -- thanks!

**Comment by smjonas** [comment]
Perfect, thanks for letting me know!
